### PR TITLE
New test to check the default value of a Trait.

### PR DESCRIPTION
**Pull request by Croshiw**
Failing for now, related issue : #386

### CODE REVIEW

**Comment by anneetien** [comment]
For technical reasons, I manually resolved the conflicts from github.
The first conflict was linked to a change in BasicInfrastructureGenerator (removing TSourcedEntity from the hierarchy of TNamedEntity)
The second conflict added TSourcedEntity in FamixTest1Generator in consequence.
However, on my image, a test remains yellow what is the problem for the Pharo 9.0 CI. But since the yellow test is related to the default value of a Trait, I don't know how to solve it.
The problem on Pharo10 CI is certainly linked to a dirty slot in the models.
@Croshiw with whom did you make this commit?
@NicolasAnquetil
@aranega are you aware of this?

**Comment by Croshiw** [comment]
Hello,

This issue was found during a Moose Dojo where I was paired with @ClotildeToullec

**Comment by aranega** [comment]
The PR only defines a new test for the case of default values in Traits. Currently, this is not managed by the generator, we need to add it.
From what I guess, the solution would be to take into consideration the traits and the all instances variables from traits applied to a class that own a default value and to generate the initialization code for it in the `initialize` method of the class.
The generator that generates the `initialize` method is the `FmxMBBehavior>>#generateIntializeFor:` method.

**Comment by Gabriel-Darbord** [comment]
The handling of default value has been changed, see #557.

**Pull request closed without merging**
