### PR TITLE
Add #isQueryable to TEntityMetaLevelDependency

### PR DESCRIPTION
**Pull request by jecisc**
It happens a lot that we need to know if en entity is queryable or not and the current way to know it can be a little slow. 

I propose to generate a method #isQueryble so that we can do a simple #select:

### CODE REVIEW

**Comment by NicolasAnquetil** [comment]
what is a "queryable" entity ?

**Comment by jecisc** [comment]
An entity that has the TEntityMetalevelDependecy trait (trait that adds everything to be queryable)

**Comment by NicolasAnquetil** [comment]
1. but what does it mean for the user of the method? Queriable by who? How?
2. did I get it rigth that you added #isQueryable to TEntityMetaLevelDependency to check that the entity uses the TEntityMetaLevelDependency trait ?

Why don't you just put in moose-Entity
```st
isQueryable
  "checks that the entity can be queried discovered in the QueryBrowser"
    ^self <uses TEntityMetaLevelDependency trait>
```
?

And I would change MiQueriesDashboardBrowser>>

**Comment by jecisc** [comment]
1) Since TEntityMetalevelDependency is part of MooseQuery, it's queryable by MooseQuery (and by extension FamixQuery since it is built on top of MooseQuery)

2) It takes time to check if an entity has a trait in its trait composition. It's really fast, except when you have 2500000 entities or more. Then it can be 20/100 times longer to look in the trait composition compared to just having a method returning a boolean. And this one is used by most of the queries of FamixQuery

**Pull request merged**
