### PR TITLE
Added CPP model

### PR DESCRIPTION
**Pull request by akevalion**
This pull request addresses these issues:
- https://github.com/moosetechnology/MooseIDE/issues/438
- https://github.com/moosetechnology/MooseIDE/issues/451

This PR modifies the baseline of Famix and adds new packages
Cpp-Generator
Cpp-Entities auto generated package
Cpp-Entities-Tests
Cpp-Parser
Cpp-Parser-Tests

### CODE REVIEW

**Comment by badetitou** [comment]
Why do we want to integrate this directly in the Famix repository and not in a sub project ? 
(and if you want, load the subproject by default)

We spent a lot of time splitting stuff. It sounds not ok to me

**Comment by badetitou** [comment]
I think you should also create a separate repo for Famix compatibility, and Famix smalltalk, and famix java.

**Comment by jecisc** [comment]
Most of it is already in this project: https://github.com/jecisc/CPPS

This could just be splitting this project in two?

**Comment by akevalion** [comment]
Hello, I have a a copy of that project https://github.com/jecisc/CPPS here https://github.com/akevalion/CPPS.
I am using the CI, to verify my changes to the new version of famix and moose.
By now you can ignore this pull request, but In a future we will need Famix-smalltalkl, famix-java, etc.

**Comment by akevalion** [comment]
I have added https://github.com/moosetechnology/Famix/issues/414
And renamed the repository to https://github.com/akevalion/Famix-CPP

**Pull request merged**
